/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-03 at 18:57:12 UTC 
 * Modify at your own risk.
 */

package com.appspot.bacsafeserver.bacsafeAPI;

/**
 * Service definition for BacsafeAPI (v1).
 *
 * <p>
 * API for BACSafe
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link BacsafeAPIRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class BacsafeAPI extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.17.0-rc of the bacsafeAPI library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://bacsafeserver.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "bacsafeAPI/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public BacsafeAPI(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  BacsafeAPI(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Buddyrequest collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code BacsafeAPI bacsafeAPI = new BacsafeAPI(...);}
   *   {@code BacsafeAPI.Buddyrequest.List request = bacsafeAPI.buddyrequest().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Buddyrequest buddyrequest() {
    return new Buddyrequest();
  }

  /**
   * The "buddyrequest" collection of methods.
   */
  public class Buddyrequest {

    /**
     * Create a request for the method "buddyrequest.acceptBuddyRequests".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link AcceptBuddyRequests#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.BuddyRequestsProtoSenderUserNameRequestedUserName}
     * @return the request
     */
    public AcceptBuddyRequests acceptBuddyRequests(com.appspot.bacsafeserver.bacsafeAPI.model.BuddyRequestsProtoSenderUserNameRequestedUserName content) throws java.io.IOException {
      AcceptBuddyRequests result = new AcceptBuddyRequests(content);
      initialize(result);
      return result;
    }

    public class AcceptBuddyRequests extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse> {

      private static final String REST_PATH = "acceptBuddyRequests";

      /**
       * Create a request for the method "buddyrequest.acceptBuddyRequests".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link AcceptBuddyRequests#execute()} method to invoke the remote
       * operation. <p> {@link AcceptBuddyRequests#initialize(com.google.api.client.googleapis.services.
       * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.BuddyRequestsProtoSenderUserNameRequestedUserName}
       * @since 1.13
       */
      protected AcceptBuddyRequests(com.appspot.bacsafeserver.bacsafeAPI.model.BuddyRequestsProtoSenderUserNameRequestedUserName content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse.class);
      }

      @Override
      public AcceptBuddyRequests setAlt(java.lang.String alt) {
        return (AcceptBuddyRequests) super.setAlt(alt);
      }

      @Override
      public AcceptBuddyRequests setFields(java.lang.String fields) {
        return (AcceptBuddyRequests) super.setFields(fields);
      }

      @Override
      public AcceptBuddyRequests setKey(java.lang.String key) {
        return (AcceptBuddyRequests) super.setKey(key);
      }

      @Override
      public AcceptBuddyRequests setOauthToken(java.lang.String oauthToken) {
        return (AcceptBuddyRequests) super.setOauthToken(oauthToken);
      }

      @Override
      public AcceptBuddyRequests setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (AcceptBuddyRequests) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public AcceptBuddyRequests setQuotaUser(java.lang.String quotaUser) {
        return (AcceptBuddyRequests) super.setQuotaUser(quotaUser);
      }

      @Override
      public AcceptBuddyRequests setUserIp(java.lang.String userIp) {
        return (AcceptBuddyRequests) super.setUserIp(userIp);
      }

      @Override
      public AcceptBuddyRequests set(String parameterName, Object value) {
        return (AcceptBuddyRequests) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "buddyrequest.getBuddyRequests".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link GetBuddyRequests#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.BuddyRequestsProtoRequestedUserName}
     * @return the request
     */
    public GetBuddyRequests getBuddyRequests(com.appspot.bacsafeserver.bacsafeAPI.model.BuddyRequestsProtoRequestedUserName content) throws java.io.IOException {
      GetBuddyRequests result = new GetBuddyRequests(content);
      initialize(result);
      return result;
    }

    public class GetBuddyRequests extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse> {

      private static final String REST_PATH = "getBuddyRequests";

      /**
       * Create a request for the method "buddyrequest.getBuddyRequests".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link GetBuddyRequests#execute()} method to invoke the remote
       * operation. <p> {@link GetBuddyRequests#initialize(com.google.api.client.googleapis.services.Abs
       * tractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.BuddyRequestsProtoRequestedUserName}
       * @since 1.13
       */
      protected GetBuddyRequests(com.appspot.bacsafeserver.bacsafeAPI.model.BuddyRequestsProtoRequestedUserName content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse.class);
      }

      @Override
      public GetBuddyRequests setAlt(java.lang.String alt) {
        return (GetBuddyRequests) super.setAlt(alt);
      }

      @Override
      public GetBuddyRequests setFields(java.lang.String fields) {
        return (GetBuddyRequests) super.setFields(fields);
      }

      @Override
      public GetBuddyRequests setKey(java.lang.String key) {
        return (GetBuddyRequests) super.setKey(key);
      }

      @Override
      public GetBuddyRequests setOauthToken(java.lang.String oauthToken) {
        return (GetBuddyRequests) super.setOauthToken(oauthToken);
      }

      @Override
      public GetBuddyRequests setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetBuddyRequests) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetBuddyRequests setQuotaUser(java.lang.String quotaUser) {
        return (GetBuddyRequests) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetBuddyRequests setUserIp(java.lang.String userIp) {
        return (GetBuddyRequests) super.setUserIp(userIp);
      }

      @Override
      public GetBuddyRequests set(String parameterName, Object value) {
        return (GetBuddyRequests) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "buddyrequest.sendBuddyRequest".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link SendBuddyRequest#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.BuddyRequestsProtoSenderUserNameRequestedUserName}
     * @return the request
     */
    public SendBuddyRequest sendBuddyRequest(com.appspot.bacsafeserver.bacsafeAPI.model.BuddyRequestsProtoSenderUserNameRequestedUserName content) throws java.io.IOException {
      SendBuddyRequest result = new SendBuddyRequest(content);
      initialize(result);
      return result;
    }

    public class SendBuddyRequest extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse> {

      private static final String REST_PATH = "usersendBuddyRequest";

      /**
       * Create a request for the method "buddyrequest.sendBuddyRequest".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link SendBuddyRequest#execute()} method to invoke the remote
       * operation. <p> {@link SendBuddyRequest#initialize(com.google.api.client.googleapis.services.Abs
       * tractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.BuddyRequestsProtoSenderUserNameRequestedUserName}
       * @since 1.13
       */
      protected SendBuddyRequest(com.appspot.bacsafeserver.bacsafeAPI.model.BuddyRequestsProtoSenderUserNameRequestedUserName content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse.class);
      }

      @Override
      public SendBuddyRequest setAlt(java.lang.String alt) {
        return (SendBuddyRequest) super.setAlt(alt);
      }

      @Override
      public SendBuddyRequest setFields(java.lang.String fields) {
        return (SendBuddyRequest) super.setFields(fields);
      }

      @Override
      public SendBuddyRequest setKey(java.lang.String key) {
        return (SendBuddyRequest) super.setKey(key);
      }

      @Override
      public SendBuddyRequest setOauthToken(java.lang.String oauthToken) {
        return (SendBuddyRequest) super.setOauthToken(oauthToken);
      }

      @Override
      public SendBuddyRequest setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (SendBuddyRequest) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public SendBuddyRequest setQuotaUser(java.lang.String quotaUser) {
        return (SendBuddyRequest) super.setQuotaUser(quotaUser);
      }

      @Override
      public SendBuddyRequest setUserIp(java.lang.String userIp) {
        return (SendBuddyRequest) super.setUserIp(userIp);
      }

      @Override
      public SendBuddyRequest set(String parameterName, Object value) {
        return (SendBuddyRequest) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Groups collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code BacsafeAPI bacsafeAPI = new BacsafeAPI(...);}
   *   {@code BacsafeAPI.Groups.List request = bacsafeAPI.groups().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Groups groups() {
    return new Groups();
  }

  /**
   * The "groups" collection of methods.
   */
  public class Groups {

    /**
     * Create a request for the method "groups.addDD".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link AddDD#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPIGroupUser}
     * @return the request
     */
    public AddDD addDD(com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPIGroupUser content) throws java.io.IOException {
      AddDD result = new AddDD(content);
      initialize(result);
      return result;
    }

    public class AddDD extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse> {

      private static final String REST_PATH = "groupsAddDD";

      /**
       * Create a request for the method "groups.addDD".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link AddDD#execute()} method to invoke the remote operation.
       * <p> {@link
       * AddDD#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPIGroupUser}
       * @since 1.13
       */
      protected AddDD(com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPIGroupUser content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse.class);
      }

      @Override
      public AddDD setAlt(java.lang.String alt) {
        return (AddDD) super.setAlt(alt);
      }

      @Override
      public AddDD setFields(java.lang.String fields) {
        return (AddDD) super.setFields(fields);
      }

      @Override
      public AddDD setKey(java.lang.String key) {
        return (AddDD) super.setKey(key);
      }

      @Override
      public AddDD setOauthToken(java.lang.String oauthToken) {
        return (AddDD) super.setOauthToken(oauthToken);
      }

      @Override
      public AddDD setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (AddDD) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public AddDD setQuotaUser(java.lang.String quotaUser) {
        return (AddDD) super.setQuotaUser(quotaUser);
      }

      @Override
      public AddDD setUserIp(java.lang.String userIp) {
        return (AddDD) super.setUserIp(userIp);
      }

      @Override
      public AddDD set(String parameterName, Object value) {
        return (AddDD) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "groups.addDrinker".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link AddDrinker#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPIGroupUser}
     * @return the request
     */
    public AddDrinker addDrinker(com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPIGroupUser content) throws java.io.IOException {
      AddDrinker result = new AddDrinker(content);
      initialize(result);
      return result;
    }

    public class AddDrinker extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse> {

      private static final String REST_PATH = "groupsAddDrinker";

      /**
       * Create a request for the method "groups.addDrinker".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link AddDrinker#execute()} method to invoke the remote
       * operation. <p> {@link
       * AddDrinker#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPIGroupUser}
       * @since 1.13
       */
      protected AddDrinker(com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPIGroupUser content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse.class);
      }

      @Override
      public AddDrinker setAlt(java.lang.String alt) {
        return (AddDrinker) super.setAlt(alt);
      }

      @Override
      public AddDrinker setFields(java.lang.String fields) {
        return (AddDrinker) super.setFields(fields);
      }

      @Override
      public AddDrinker setKey(java.lang.String key) {
        return (AddDrinker) super.setKey(key);
      }

      @Override
      public AddDrinker setOauthToken(java.lang.String oauthToken) {
        return (AddDrinker) super.setOauthToken(oauthToken);
      }

      @Override
      public AddDrinker setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (AddDrinker) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public AddDrinker setQuotaUser(java.lang.String quotaUser) {
        return (AddDrinker) super.setQuotaUser(quotaUser);
      }

      @Override
      public AddDrinker setUserIp(java.lang.String userIp) {
        return (AddDrinker) super.setUserIp(userIp);
      }

      @Override
      public AddDrinker set(String parameterName, Object value) {
        return (AddDrinker) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "groups.createGroup".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link CreateGroup#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.GroupsProtoGroupName}
     * @return the request
     */
    public CreateGroup createGroup(com.appspot.bacsafeserver.bacsafeAPI.model.GroupsProtoGroupName content) throws java.io.IOException {
      CreateGroup result = new CreateGroup(content);
      initialize(result);
      return result;
    }

    public class CreateGroup extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse> {

      private static final String REST_PATH = "groupsCreateGroup";

      /**
       * Create a request for the method "groups.createGroup".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link CreateGroup#execute()} method to invoke the remote
       * operation. <p> {@link
       * CreateGroup#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.GroupsProtoGroupName}
       * @since 1.13
       */
      protected CreateGroup(com.appspot.bacsafeserver.bacsafeAPI.model.GroupsProtoGroupName content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse.class);
      }

      @Override
      public CreateGroup setAlt(java.lang.String alt) {
        return (CreateGroup) super.setAlt(alt);
      }

      @Override
      public CreateGroup setFields(java.lang.String fields) {
        return (CreateGroup) super.setFields(fields);
      }

      @Override
      public CreateGroup setKey(java.lang.String key) {
        return (CreateGroup) super.setKey(key);
      }

      @Override
      public CreateGroup setOauthToken(java.lang.String oauthToken) {
        return (CreateGroup) super.setOauthToken(oauthToken);
      }

      @Override
      public CreateGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (CreateGroup) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public CreateGroup setQuotaUser(java.lang.String quotaUser) {
        return (CreateGroup) super.setQuotaUser(quotaUser);
      }

      @Override
      public CreateGroup setUserIp(java.lang.String userIp) {
        return (CreateGroup) super.setUserIp(userIp);
      }

      @Override
      public CreateGroup set(String parameterName, Object value) {
        return (CreateGroup) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "groups.getGroupInfo".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link GetGroupInfo#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.GroupsProtoGroupName}
     * @return the request
     */
    public GetGroupInfo getGroupInfo(com.appspot.bacsafeserver.bacsafeAPI.model.GroupsProtoGroupName content) throws java.io.IOException {
      GetGroupInfo result = new GetGroupInfo(content);
      initialize(result);
      return result;
    }

    public class GetGroupInfo extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.Groups> {

      private static final String REST_PATH = "groupsGetGroupInfo";

      /**
       * Create a request for the method "groups.getGroupInfo".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link GetGroupInfo#execute()} method to invoke the remote
       * operation. <p> {@link
       * GetGroupInfo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.GroupsProtoGroupName}
       * @since 1.13
       */
      protected GetGroupInfo(com.appspot.bacsafeserver.bacsafeAPI.model.GroupsProtoGroupName content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.Groups.class);
      }

      @Override
      public GetGroupInfo setAlt(java.lang.String alt) {
        return (GetGroupInfo) super.setAlt(alt);
      }

      @Override
      public GetGroupInfo setFields(java.lang.String fields) {
        return (GetGroupInfo) super.setFields(fields);
      }

      @Override
      public GetGroupInfo setKey(java.lang.String key) {
        return (GetGroupInfo) super.setKey(key);
      }

      @Override
      public GetGroupInfo setOauthToken(java.lang.String oauthToken) {
        return (GetGroupInfo) super.setOauthToken(oauthToken);
      }

      @Override
      public GetGroupInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetGroupInfo) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetGroupInfo setQuotaUser(java.lang.String quotaUser) {
        return (GetGroupInfo) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetGroupInfo setUserIp(java.lang.String userIp) {
        return (GetGroupInfo) super.setUserIp(userIp);
      }

      @Override
      public GetGroupInfo set(String parameterName, Object value) {
        return (GetGroupInfo) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "groups.isGroupActive".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link IsGroupActive#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.GroupsProtoGroupName}
     * @return the request
     */
    public IsGroupActive isGroupActive(com.appspot.bacsafeserver.bacsafeAPI.model.GroupsProtoGroupName content) throws java.io.IOException {
      IsGroupActive result = new IsGroupActive(content);
      initialize(result);
      return result;
    }

    public class IsGroupActive extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse> {

      private static final String REST_PATH = "groupsIsGroupActive";

      /**
       * Create a request for the method "groups.isGroupActive".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link IsGroupActive#execute()} method to invoke the remote
       * operation. <p> {@link IsGroupActive#initialize(com.google.api.client.googleapis.services.Abstra
       * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.GroupsProtoGroupName}
       * @since 1.13
       */
      protected IsGroupActive(com.appspot.bacsafeserver.bacsafeAPI.model.GroupsProtoGroupName content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse.class);
      }

      @Override
      public IsGroupActive setAlt(java.lang.String alt) {
        return (IsGroupActive) super.setAlt(alt);
      }

      @Override
      public IsGroupActive setFields(java.lang.String fields) {
        return (IsGroupActive) super.setFields(fields);
      }

      @Override
      public IsGroupActive setKey(java.lang.String key) {
        return (IsGroupActive) super.setKey(key);
      }

      @Override
      public IsGroupActive setOauthToken(java.lang.String oauthToken) {
        return (IsGroupActive) super.setOauthToken(oauthToken);
      }

      @Override
      public IsGroupActive setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (IsGroupActive) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public IsGroupActive setQuotaUser(java.lang.String quotaUser) {
        return (IsGroupActive) super.setQuotaUser(quotaUser);
      }

      @Override
      public IsGroupActive setUserIp(java.lang.String userIp) {
        return (IsGroupActive) super.setUserIp(userIp);
      }

      @Override
      public IsGroupActive set(String parameterName, Object value) {
        return (IsGroupActive) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Userinfo collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code BacsafeAPI bacsafeAPI = new BacsafeAPI(...);}
   *   {@code BacsafeAPI.Userinfo.List request = bacsafeAPI.userinfo().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Userinfo userinfo() {
    return new Userinfo();
  }

  /**
   * The "userinfo" collection of methods.
   */
  public class Userinfo {

    /**
     * Create a request for the method "userinfo.createBuddies".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link CreateBuddies#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameBuddies}
     * @return the request
     */
    public CreateBuddies createBuddies(com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameBuddies content) throws java.io.IOException {
      CreateBuddies result = new CreateBuddies(content);
      initialize(result);
      return result;
    }

    public class CreateBuddies extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse> {

      private static final String REST_PATH = "userInfoCreateBuddies";

      /**
       * Create a request for the method "userinfo.createBuddies".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link CreateBuddies#execute()} method to invoke the remote
       * operation. <p> {@link CreateBuddies#initialize(com.google.api.client.googleapis.services.Abstra
       * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameBuddies}
       * @since 1.13
       */
      protected CreateBuddies(com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameBuddies content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse.class);
      }

      @Override
      public CreateBuddies setAlt(java.lang.String alt) {
        return (CreateBuddies) super.setAlt(alt);
      }

      @Override
      public CreateBuddies setFields(java.lang.String fields) {
        return (CreateBuddies) super.setFields(fields);
      }

      @Override
      public CreateBuddies setKey(java.lang.String key) {
        return (CreateBuddies) super.setKey(key);
      }

      @Override
      public CreateBuddies setOauthToken(java.lang.String oauthToken) {
        return (CreateBuddies) super.setOauthToken(oauthToken);
      }

      @Override
      public CreateBuddies setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (CreateBuddies) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public CreateBuddies setQuotaUser(java.lang.String quotaUser) {
        return (CreateBuddies) super.setQuotaUser(quotaUser);
      }

      @Override
      public CreateBuddies setUserIp(java.lang.String userIp) {
        return (CreateBuddies) super.setUserIp(userIp);
      }

      @Override
      public CreateBuddies set(String parameterName, Object value) {
        return (CreateBuddies) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "userinfo.getUserBuddiesInfo".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link GetUserBuddiesInfo#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserName}
     * @return the request
     */
    public GetUserBuddiesInfo getUserBuddiesInfo(com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserName content) throws java.io.IOException {
      GetUserBuddiesInfo result = new GetUserBuddiesInfo(content);
      initialize(result);
      return result;
    }

    public class GetUserBuddiesInfo extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.UserInfo> {

      private static final String REST_PATH = "userInfoGetBuddiesInfo";

      /**
       * Create a request for the method "userinfo.getUserBuddiesInfo".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link GetUserBuddiesInfo#execute()} method to invoke the remote
       * operation. <p> {@link GetUserBuddiesInfo#initialize(com.google.api.client.googleapis.services.A
       * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserName}
       * @since 1.13
       */
      protected GetUserBuddiesInfo(com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserName content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.UserInfo.class);
      }

      @Override
      public GetUserBuddiesInfo setAlt(java.lang.String alt) {
        return (GetUserBuddiesInfo) super.setAlt(alt);
      }

      @Override
      public GetUserBuddiesInfo setFields(java.lang.String fields) {
        return (GetUserBuddiesInfo) super.setFields(fields);
      }

      @Override
      public GetUserBuddiesInfo setKey(java.lang.String key) {
        return (GetUserBuddiesInfo) super.setKey(key);
      }

      @Override
      public GetUserBuddiesInfo setOauthToken(java.lang.String oauthToken) {
        return (GetUserBuddiesInfo) super.setOauthToken(oauthToken);
      }

      @Override
      public GetUserBuddiesInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetUserBuddiesInfo) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetUserBuddiesInfo setQuotaUser(java.lang.String quotaUser) {
        return (GetUserBuddiesInfo) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetUserBuddiesInfo setUserIp(java.lang.String userIp) {
        return (GetUserBuddiesInfo) super.setUserIp(userIp);
      }

      @Override
      public GetUserBuddiesInfo set(String parameterName, Object value) {
        return (GetUserBuddiesInfo) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "userinfo.setGroups".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link SetGroups#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameGroups}
     * @return the request
     */
    public SetGroups setGroups(com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameGroups content) throws java.io.IOException {
      SetGroups result = new SetGroups(content);
      initialize(result);
      return result;
    }

    public class SetGroups extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse> {

      private static final String REST_PATH = "userInfoSetGroups";

      /**
       * Create a request for the method "userinfo.setGroups".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link SetGroups#execute()} method to invoke the remote
       * operation. <p> {@link
       * SetGroups#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameGroups}
       * @since 1.13
       */
      protected SetGroups(com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameGroups content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse.class);
      }

      @Override
      public SetGroups setAlt(java.lang.String alt) {
        return (SetGroups) super.setAlt(alt);
      }

      @Override
      public SetGroups setFields(java.lang.String fields) {
        return (SetGroups) super.setFields(fields);
      }

      @Override
      public SetGroups setKey(java.lang.String key) {
        return (SetGroups) super.setKey(key);
      }

      @Override
      public SetGroups setOauthToken(java.lang.String oauthToken) {
        return (SetGroups) super.setOauthToken(oauthToken);
      }

      @Override
      public SetGroups setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (SetGroups) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public SetGroups setQuotaUser(java.lang.String quotaUser) {
        return (SetGroups) super.setQuotaUser(quotaUser);
      }

      @Override
      public SetGroups setUserIp(java.lang.String userIp) {
        return (SetGroups) super.setUserIp(userIp);
      }

      @Override
      public SetGroups set(String parameterName, Object value) {
        return (SetGroups) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "userinfo.updateUserBAC".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link UpdateUserBAC#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameCurBAC}
     * @return the request
     */
    public UpdateUserBAC updateUserBAC(com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameCurBAC content) throws java.io.IOException {
      UpdateUserBAC result = new UpdateUserBAC(content);
      initialize(result);
      return result;
    }

    public class UpdateUserBAC extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse> {

      private static final String REST_PATH = "userBACInfoUpdate";

      /**
       * Create a request for the method "userinfo.updateUserBAC".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link UpdateUserBAC#execute()} method to invoke the remote
       * operation. <p> {@link UpdateUserBAC#initialize(com.google.api.client.googleapis.services.Abstra
       * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameCurBAC}
       * @since 1.13
       */
      protected UpdateUserBAC(com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameCurBAC content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse.class);
      }

      @Override
      public UpdateUserBAC setAlt(java.lang.String alt) {
        return (UpdateUserBAC) super.setAlt(alt);
      }

      @Override
      public UpdateUserBAC setFields(java.lang.String fields) {
        return (UpdateUserBAC) super.setFields(fields);
      }

      @Override
      public UpdateUserBAC setKey(java.lang.String key) {
        return (UpdateUserBAC) super.setKey(key);
      }

      @Override
      public UpdateUserBAC setOauthToken(java.lang.String oauthToken) {
        return (UpdateUserBAC) super.setOauthToken(oauthToken);
      }

      @Override
      public UpdateUserBAC setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (UpdateUserBAC) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public UpdateUserBAC setQuotaUser(java.lang.String quotaUser) {
        return (UpdateUserBAC) super.setQuotaUser(quotaUser);
      }

      @Override
      public UpdateUserBAC setUserIp(java.lang.String userIp) {
        return (UpdateUserBAC) super.setUserIp(userIp);
      }

      @Override
      public UpdateUserBAC set(String parameterName, Object value) {
        return (UpdateUserBAC) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "userinfo.updateUserDrinkCount".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link UpdateUserDrinkCount#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameDrinkCount}
     * @return the request
     */
    public UpdateUserDrinkCount updateUserDrinkCount(com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameDrinkCount content) throws java.io.IOException {
      UpdateUserDrinkCount result = new UpdateUserDrinkCount(content);
      initialize(result);
      return result;
    }

    public class UpdateUserDrinkCount extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse> {

      private static final String REST_PATH = "userDrinkCountInfoUpdate";

      /**
       * Create a request for the method "userinfo.updateUserDrinkCount".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link UpdateUserDrinkCount#execute()} method to invoke the
       * remote operation. <p> {@link UpdateUserDrinkCount#initialize(com.google.api.client.googleapis.s
       * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
       * after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameDrinkCount}
       * @since 1.13
       */
      protected UpdateUserDrinkCount(com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameDrinkCount content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse.class);
      }

      @Override
      public UpdateUserDrinkCount setAlt(java.lang.String alt) {
        return (UpdateUserDrinkCount) super.setAlt(alt);
      }

      @Override
      public UpdateUserDrinkCount setFields(java.lang.String fields) {
        return (UpdateUserDrinkCount) super.setFields(fields);
      }

      @Override
      public UpdateUserDrinkCount setKey(java.lang.String key) {
        return (UpdateUserDrinkCount) super.setKey(key);
      }

      @Override
      public UpdateUserDrinkCount setOauthToken(java.lang.String oauthToken) {
        return (UpdateUserDrinkCount) super.setOauthToken(oauthToken);
      }

      @Override
      public UpdateUserDrinkCount setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (UpdateUserDrinkCount) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public UpdateUserDrinkCount setQuotaUser(java.lang.String quotaUser) {
        return (UpdateUserDrinkCount) super.setQuotaUser(quotaUser);
      }

      @Override
      public UpdateUserDrinkCount setUserIp(java.lang.String userIp) {
        return (UpdateUserDrinkCount) super.setUserIp(userIp);
      }

      @Override
      public UpdateUserDrinkCount set(String parameterName, Object value) {
        return (UpdateUserDrinkCount) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "userinfo.userAccountSetup".
     *
     * This request holds the parameters needed by the bacsafeAPI server.  After setting any optional
     * parameters, call the {@link UserAccountSetup#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameFirstNameLastName}
     * @return the request
     */
    public UserAccountSetup userAccountSetup(com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameFirstNameLastName content) throws java.io.IOException {
      UserAccountSetup result = new UserAccountSetup(content);
      initialize(result);
      return result;
    }

    public class UserAccountSetup extends BacsafeAPIRequest<com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse> {

      private static final String REST_PATH = "userInfoSetup";

      /**
       * Create a request for the method "userinfo.userAccountSetup".
       *
       * This request holds the parameters needed by the the bacsafeAPI server.  After setting any
       * optional parameters, call the {@link UserAccountSetup#execute()} method to invoke the remote
       * operation. <p> {@link UserAccountSetup#initialize(com.google.api.client.googleapis.services.Abs
       * tractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameFirstNameLastName}
       * @since 1.13
       */
      protected UserAccountSetup(com.appspot.bacsafeserver.bacsafeAPI.model.UserInfoProtoUserNameFirstNameLastName content) {
        super(BacsafeAPI.this, "POST", REST_PATH, content, com.appspot.bacsafeserver.bacsafeAPI.model.BacsafeAPILogResponse.class);
      }

      @Override
      public UserAccountSetup setAlt(java.lang.String alt) {
        return (UserAccountSetup) super.setAlt(alt);
      }

      @Override
      public UserAccountSetup setFields(java.lang.String fields) {
        return (UserAccountSetup) super.setFields(fields);
      }

      @Override
      public UserAccountSetup setKey(java.lang.String key) {
        return (UserAccountSetup) super.setKey(key);
      }

      @Override
      public UserAccountSetup setOauthToken(java.lang.String oauthToken) {
        return (UserAccountSetup) super.setOauthToken(oauthToken);
      }

      @Override
      public UserAccountSetup setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (UserAccountSetup) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public UserAccountSetup setQuotaUser(java.lang.String quotaUser) {
        return (UserAccountSetup) super.setQuotaUser(quotaUser);
      }

      @Override
      public UserAccountSetup setUserIp(java.lang.String userIp) {
        return (UserAccountSetup) super.setUserIp(userIp);
      }

      @Override
      public UserAccountSetup set(String parameterName, Object value) {
        return (UserAccountSetup) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link BacsafeAPI}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link BacsafeAPI}. */
    @Override
    public BacsafeAPI build() {
      return new BacsafeAPI(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link BacsafeAPIRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setBacsafeAPIRequestInitializer(
        BacsafeAPIRequestInitializer bacsafeapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(bacsafeapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
